---
language: generic

sudo: required

services:
  - docker

before_script:
  - docker pull thebiggerguy/docker-flatpak-dev
  - docker run --privileged -d -p 127.0.0.1:80:4567 thebiggerguy/docker-flatpak-dev /bin/sh -c "flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo && flatpak install flathub org.gnome.Platform 3.26 && flatpak install flathub org.gnome.Sdk 3.26 && mkdir flatpakBuild && cd flatpakBuild && flatpak-builder build --repo=repo hydrapaper ../misc/org.gabmus.hydrapapergit.json --force-clean && flatpak build-bundle repo hydrapaper-$(git describe --long --tags --always).flatpak org.gabmus.hydrapaper"

script:
  - ls -a
