---
language: generic

sudo: required

services:
  - docker

before_script:
  - "docker pull ubuntu"

script:
- docker run --privileged -it ubuntu /bin/bash -c "add-apt-repository ppa:alexlarsson/flatpak -y; apt-get update; apt-get install -y git flatpak flatpak-builder; git clone https://github.com/gabmus/HydraPaper /root/hydrapaper; flatpak-builder build --repo=/root/repo hydrapaper /root/hydrapaper/misc/org.gabmus.hydrapapergit.json --force-clean; flatpak build-bundle /root/repo hydrapaper-$(git -C /root/hydrapaper describe --long --tags --always).flatpak org.gabmus.hydrapaper"
