---
language: generic

sudo: required

services:
  - docker

before_script:
  - "docker pull thebiggerguy/docker-flatpak-dev"

script:
- docker run --privileged -it --rm --cap-add=SYS_CHROOT thebiggerguy/docker-flatpak-dev "find / -maxdepth 2 -type d -ls"

#mkdir -p /build/hydrapaper && git clone https://github.com/gabmus/HydraPaper /build/hydrapaper && flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo && flatpak install flathub org.gnome.Platform 3.26 && flatpak install flathub org.gnome.Sdk 3.26 && flatpak-builder build --repo=/build/repo hydrapaper /build/hydrapaper/misc/org.gabmus.hydrapapergit.json --force-clean && flatpak build-bundle /build/repo hydrapaper-$(git -C /build/hydrapaper describe --long --tags --always).flatpak org.gabmus.hydrapaper"
